app:
  datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/booklist
      username: postgres
      password: password
      pool-size: 100
spring:
  flyway:
    locations: classpath:db.migration
    validateMigrationNaming: false
    enabled: false
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 300
  mongodb:
    uri: mongodb://localhost:27017/bookstore

jpa:
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



